//Upcoming
export const GET_MOVIES_START = "GET_MOVIES_START"
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS"
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED"
//Trending
export const GET_TRENDING_START = "GET_TRENDING_START"
export const GET_TRENDING_FAILED = "GET_TRENDING_FAILED"
export const GET_TRENDING_SUCCESS = "GET_TRENDING_SUCCESS"
//Discover
export const GET_DISCOVER_START = "GET_DISCOVER_START"
export const GET_DISCOVER_FAILED = "GET_DISCOVER_FAILED"
export const GET_DISCOVER_SUCCESS = "GET_DISCOVER_SUCCESS"
//Detail Movie
export const GET_DETAIL_MOVIE_START = "GET_DETAIL_MOVIE_START"
export const GET_DETAIL_MOVIE_SUCCESS = "GET_DETAIL_MOVIE_SUCCESS"
export const GET_DETAIL_MOVIE_FAILED = "GET_DETAIL_MOVIE_FAILED"